n = input('Digite algo: ')
print('O tipo primitivo desse valor: ',type(n))
print('So tem espacos? ',n.isspace())
print('E um numero? ',n.isnumeric())
print('E alfabetico?',n.isalpha())
print('E alfanumero? ',n.isalnum())
print('Esta em maiuscula? ',n.isupper())
print('Esta em minuscula',n.islower())
print('Esta capitalizada',n.istitle())
